name: flutter_clean_template
description: flutter_clean_template
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter_bloc: ^8.1.0
  get_it: ^7.2.0
  equatable: ^2.0.0
  freezed: ^2.0.4
  freezed_annotation: ^2.1.0
  dio: ^4.0.0
  connectivity_plus: ^2.1.0
  logger: ^1.3.0

  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

dev_dependencies:
  build_runner: ^2.2.0
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true




